
package ec.edu.espe.stylesirelia.view;


import com.mongodb.BasicDBObject;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import static com.mongodb.client.model.Filters.eq;
import ec.edu.espe.stylesirelia.controller.UserController;
import ec.edu.espe.stylesirelia.model.Connection;
import ec.edu.espe.stylesirelia.model.User;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author Luis Burbano, DCCO- ESPE, BettaCoders
 */
public class FrmLogin extends javax.swing.JFrame {


    public FrmLogin() {
        Connection connection = new Connection();
        connection.connectionDataBase();
        
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        String path = System.getProperty("user.dir");
//        ImageIcon img = new ImageIcon(path +"\\src\\ec\\edu\\espe\\stylesirelia\\sources\\logoBettaCoders.png");
//        this.setIconImage(img.getImage());
        this.setTitle("Login Window");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLeaveLogin = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        btnEnterLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldUser = new javax.swing.JTextField();
        labelWelcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLeaveLogin.setBackground(new java.awt.Color(125, 9, 119));
        btnLeaveLogin.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        btnLeaveLogin.setForeground(new java.awt.Color(242, 242, 242));
        btnLeaveLogin.setText("Leave");
        btnLeaveLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLeaveLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 170, 70));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 252, 230, 40));

        btnEnterLogin.setBackground(new java.awt.Color(125, 9, 119));
        btnEnterLogin.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        btnEnterLogin.setForeground(new java.awt.Color(242, 242, 242));
        btnEnterLogin.setText("Enter");
        btnEnterLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnterLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 170, 70));

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("Password:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        textFieldUser.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jPanel1.add(textFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 230, -1));

        labelWelcome.setFont(new java.awt.Font("Freestyle Script", 0, 65)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(242, 242, 242));
        labelWelcome.setText("Welcome to Styles by Irelia");
        jPanel1.add(labelWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 690, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLeaveLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveLoginActionPerformed
        System.exit(0);

    }//GEN-LAST:event_btnLeaveLoginActionPerformed

    private void btnEnterLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterLoginActionPerformed

        User user;
        user = new User(textFieldUser.getText(), new String(passwordField.getPassword()));
        UserController userController = new UserController(user, "users");
        
        MongoCollection<Document> m = userController.getMongoCollection();
        
        Document doc = m.find(user.buildDocument()).first();
        
        if(doc!=null){
            FrmStylesIreliaMenu frmStylesIreliaMenu = new FrmStylesIreliaMenu();
            JOptionPane.showMessageDialog(null, "Welcome to the system");
            this.setVisible(false);
            frmStylesIreliaMenu.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "A one value is incorrect try again");
        }
        
        
        
        
        

     
        
    }//GEN-LAST:event_btnEnterLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterLogin;
    private javax.swing.JButton btnLeaveLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField textFieldUser;
    // End of variables declaration//GEN-END:variables
}
