package ec.edu.espe.stylesirelia.view;

import com.toedter.calendar.JDateChooser;
import ec.edu.espe.stylesirelia.controller.TurnController;
import ec.edu.espe.stylesirelia.controller.Connection;
import ec.edu.espe.stylesirelia.model.Turn;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import ec.edu.espe.stylesirelia.controller.Connection;

/**
 *
 * @author Joel Arguello, DCCO-ESPE, BETTACODDERS
 */
public class FrmTurn extends javax.swing.JFrame {

    SimpleDateFormat formDate = new SimpleDateFormat("dd-MM-yyyy");
    private TurnController cTurn;
    public String getDate(JDateChooser jdDate) {
        if (jdDate.getDate() != null) {
            return formDate.format(jdDate.getDate());
        } else {
            return null;
        }

    }

    /**
     * Creates new form FrmTurn
     */
    public FrmTurn() {
        initComponents();
        Connection.connectionDataBase();
        cTurn = new TurnController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dtcServiceTurn = new com.toedter.calendar.JDateChooser();
        btnRegisterTurn = new javax.swing.JButton();
        cmbService = new javax.swing.JComboBox<>();
        btnBackToMenu = new javax.swing.JButton();
        txtGetATurn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuStylesIrelia = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        jMenu1.setText("Styles Irelia");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("About");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Login Stylist");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Products");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Help");
        jMenuBar1.add(jMenu5);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Select the service:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 133, -1, -1));

        dtcServiceTurn.setMaxSelectableDate(new java.util.Date(1672552916000L));
        dtcServiceTurn.setMinSelectableDate(new java.util.Date(1657605716000L));
        jPanel1.add(dtcServiceTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 70, 176, -1));

        btnRegisterTurn.setText("Register turn");
        btnRegisterTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterTurnActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegisterTurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 216, -1, -1));

        cmbService.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hair Cut", "Massages", "Water circuits" }));
        cmbService.setToolTipText("");
        jPanel1.add(cmbService, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 130, 176, -1));

        btnBackToMenu.setText("Back to menu");
        btnBackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnBackToMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 216, -1, -1));

        txtGetATurn.setText("Get a turn");
        jPanel1.add(txtGetATurn, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 25, -1, -1));

        jLabel1.setText("Select the date:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 70, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ec/edu/espe/stylesirelia/sources/bg-logo.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, -80, -1, -1));

        mnuStylesIrelia.setText("Styles Irelia");
        mnuStylesIrelia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuStylesIreliaActionPerformed(evt);
            }
        });
        jMenuBar2.add(mnuStylesIrelia);

        jMenu6.setText("Login Stylist");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Products");
        jMenuBar2.add(jMenu7);

        jMenu8.setText("Help");
        jMenuBar2.add(jMenu8);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void mnuStylesIreliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuStylesIreliaActionPerformed

    }//GEN-LAST:event_mnuStylesIreliaActionPerformed

    private void btnBackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenuActionPerformed
//        FrmStylesirelia frmStylesirelia;
//        frmStylesirelia = new FrmStylesirelia();
//        frmStylesirelia.setVisible(true);
//        this.setVisible(false);
    }//GEN-LAST:event_btnBackToMenuActionPerformed

    private void btnRegisterTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterTurnActionPerformed
        JOptionPane.showMessageDialog(this, "Select Date is: " + getDate(dtcServiceTurn));
        String v;
        v = formDate.format(dtcServiceTurn.getDate());

        Turn turn = new Turn(1, formDate.format(dtcServiceTurn.getDate()), v, v, v);
        
        cTurn.create(cTurn.buildDocument(turn));

    }//GEN-LAST:event_btnRegisterTurnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTurn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTurn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTurn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTurn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTurn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToMenu;
    private javax.swing.JButton btnRegisterTurn;
    private javax.swing.JComboBox<String> cmbService;
    private com.toedter.calendar.JDateChooser dtcServiceTurn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnuStylesIrelia;
    private javax.swing.JLabel txtGetATurn;
    // End of variables declaration//GEN-END:variables
}
